from xobjects.context import specialize_source

todo = [
        {'src_file': './linear_interpolators.h',
         'out_file': '../src_autogenerated/linear_interpolators_cpu.c',
         'context': 'cpu',
        },
        {'src_file': './linear_interpolators.h',
         'out_file': '../src_autogenerated/linear_interpolators_opencl.clh',
         'context': 'opencl',
        },
        {'src_file': './linear_interpolators.h',
         'out_file': '../src_autogenerated/linear_interpolators_cuda.cu',
         'context': 'cuda',
        },
    ]

for job in todo:

    fname = job['src_file']
    newfname = job['out_file']
    context = job['context']


    with open(fname, 'r') as fid:
        source = fid.read()

    with open(newfname, 'w') as fid:
        fid.write(specialize_source(source, specialize_for=context))
